### ISSUE TITLE
New Insight: Meta-posts / Posts about the service

### ISSUE THREAD

**Issue by adampash** [ThinkUpLLC/ThinkUp#1977]
# One-liner

Meta-posts; Posts about the service
# Full explainer

One common pitfall of social media is the tendency to use a service as a platform to... talk about the service. This insight provides perspective and potentially challenges the user to think about the conversations she's having.
# Audience for the insight

This insight works for Twitter and Facebook. Most likely, it serves users with more activity.
# How often this insight runs
- [ ] One-time only, if it's never appeared before
- [ ] First crawl only
- [ ] Daily
- [x] Weekly
- [ ] Monthly
- [ ] Yearly
- [ ] Triggered by a data event

Could be either a good mid-week check-in or beginning/end-of-week. 
# Headline
- It's %service all the way down
- Tweets on tweets on tweets
- Tweetin' 'bout Twitter
- Feelings for Facebook
- Feeding the news feed
# Body
- %username mentioned %service or %post_type in %total %post_types this week. That's roughly %percent of %username's total %post_types for the week.
# Criteria and logic
- Insight requires a word or post count of network-relevant words. For Twitter, that'd include "twitter" and "tweets". For Facebook, include "facebook", "newsfeed", "news feed" ("posts" is probably too generic of a term).
- Require's last week's posts.
- If this insight was triggered in the week immediately preceeding the current insight, compare totals week over week.
- If baseline matches, append "[down/up] from %last_week_percent last week"
- The minimum threshold should be anything > 0
# Included elements
- [x] Headline
- [x] Text
- [x] Header image (image off to the left in side-by-side style insights)
- [ ] Hero image (giant image on top)
- [ ] List of user(s)
- [ ] List of post(s)
- [ ] List of link(s)
- [ ] Action button
- [ ] Line chart
- [ ] Bar chart
- [ ] Other viz
- [ ] Other graphic treatment

We could potentially look for/create some fun recursion images — e.g., http://nerdnirvana.org/wp-content/uploads/2010/04/Recursive-Wil-Wheaton.jpg
