### ISSUE TITLE
New Insight: Word count milestones

### ISSUE THREAD

**Issue by adampash** [ThinkUpLLC/ThinkUp#1993]
# One-liner

Word count milestones
# Full explainer

The internet makes everyone into a writer/publisher. This insight brings that idea into focus by quantifying the words poured into Twitter and Facebook. Ideally, it will make the user feel proud, or even just amused. 
# Audience for the insight

This insight works for Twitter and Facebook.

It serves users with more activity, if only b/c they're more likely to trigger more milestones.

This is not a first-run insight.
# How often this insight runs
- [ ] One-time only, if it's never appeared before
- [ ] First crawl only
- [ ] Daily
- [ ] Weekly
- [ ] Monthly
- [ ] Yearly
- [x] Triggered by a data event

This insight should be triggered by word counts since previous baseline. 
# Headline
- A thousand words is worth a picture
# Body
- %username poured 1,000 more words into Twitter since %last_1000_date, averaging about %avg_words_per_day. That brings the grand total to %total_word_count.

If %total_word_count surpasses length of a book, then append:
- That’s just over one %surpassed_book_count, 140 characters at a time.

Old Man and the Sea: 26,601
Slaughterhouse-Five: 49,459
Lord of the Flies: 59,900
Nineteen Eighty-Four: 88,942
To Kill A Mockingbird: 99,121
Crime and Punishment: 211,591
Middlemarch: 316,059
War and Peace: 587,287
(This list is really euro-centric — could be improved; [[via]](http://indefeasible.wordpress.com/2008/05/03/great-novels-and-word-count/))
# Criteria and logic
- This data needs raw word counts of the user's posts. 
- The insight compares to the previous baseline to calculate how many words/day go into the service. Baseline might also be used to ensure user doesn't get repeat-triggers for a book.
- If possible, it would be good if we could adjust the trigger amount depending on the user. E.g., more prolific users might be better at 5k or even 10k words. Goal would be to not trigger more than once/week — ideally wouldn't trigger more than once or twice a month.
# Included elements
- [x] Headline
- [x] Text
- [ ] Header image (image off to the left in side-by-side style insights)
- [x] Hero image (giant image on top)
- [ ] List of user(s)
- [ ] List of post(s)
- [ ] List of link(s)
- [ ] Action button
- [ ] Line chart
- [ ] Bar chart
- [ ] Other viz
- [ ] Other graphic treatment

I think this could be a fun insight to play with different images/gifs. E.g.:

![all that typing](https://unionmetrics.com/wp-content/themes/merle/img/team/spirit/chloe-spirit.gif)
![gibberish](http://25.media.tumblr.com/755891c4fc55531e95c8b72287eece96/tumblr_mqta5ebKh71qmgxwso1_500.gif)

Though good gifs can be a little so-so in terms of licensing.
