### ISSUE TITLE
New Insight: Total posts milestone

### ISSUE THREAD

**Issue by adampash** [ThinkUpLLC/ThinkUp#2047]
# One-liner

Post count milestones.
# Full explainer

People like assigning significance to nice, big, round numbers. This insight does that! It gives the user a heads up when she crosses certain big number milestones. It should give the user a little bit 'o fun to see these "momentous" posts.
# Audience for the insight

This insight works for Twitter, Facebook, and Instagram. It serves users with more activity.
# How often this insight runs
- [x] Always (triggered by a data event, check the data and update insight on every crawl)
- [ ] Daily (check the data once a day, don't regenerate every crawl)
- [ ] Weekly on a fixed day (specify day of week per network to space these out)
- [ ] Monthly on a fixed day with bonus magic day within first 2 weeks of use (specify day of month per network to space these out)
- [ ] Annual on a fixed date (specify day of year)
- [ ] Annual every 365 days from first appearance
# Headline
- your #total'th %post_type

Emphasis: Medium
# Body

I considered a lot of different options for the body, but every angle I took felt too leading and unnecessary. To me, this one completely works just to embed the post, presented without comment.
# Criteria and logic

This insight needs to track the running total of the user's posts. I'm thinking we trigger the insight for every 1,000 tweets/posts/pics. 

@anildash I'm curious: I've got this insight running every 1k posts, but as an extremely prolific tweeter, would that be overkill for you? Would it be better to be something like:

```
if total < 20,000
  trigger on every 1k
if total > 20,000
  trigger every 5k
```

Or something like that?

On Twitter, this should count tweets and replies but not retweets.

On Facebook, this should count user posts but not comments.

There are no baselines, and no minimum threshold.
# Included elements
- [x] Headline
- [ ] Text
- [ ] Header image (image off to the left in side-by-side style insights)
- [ ] Hero image (giant image on top)
- [ ] List of user(s)
- [x] List of post(s)
- [ ] List of link(s)
- [ ] Action button (please specify button label and URL button should link to)
- [ ] Line chart
- [ ] Bar chart
- [ ] Other viz
- [ ] Other graphic treatment
## Priority
- [ ] High
- [x] Medium
- [ ] Low
